app_news/urls.py
from django.urls import path
from .views import (
    NewsListView,
    NewsDetailFormView,
    MyLoginView,
    MyLogoutView,
    RegisterView,
    ProfileView,
    NewsCreate, NewsFormEdit)

urlpatterns = [
    path('news/', NewsListView.as_view(), name='news'),
    path('news/<int:id>/edit/', NewsFormEdit.as_view(), name='news-edit'),
    path('news/<int:pk>/', NewsDetailFormView.as_view(), name='news-detail'),
    path('news/create/', NewsCreate.as_view(), name='news-create'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_news.urls')),
]

app_news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=40, verbose_name='тэг')


class News(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    content = models.TextField(verbose_name='Содержание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')
    active = models.BooleanField(default=False, verbose_name='Активность')
    tags = models.ManyToManyField(Tag, null=True, verbose_name='Тэги', related_name='news')

    def get_absolute_url(self):
        return reverse('news')

    class Meta:
        ordering = ['-created_at']


class Comments(models.Model):
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        related_name='comments'
    )
    user_name = models.CharField(max_length=100, verbose_name='Имя пользователя')
    text = models.TextField(verbose_name='Комментарий')
    news = models.ForeignKey(News, null=True, on_delete=models.CASCADE, verbose_name='Новость', related_name='comments')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    city = models.CharField(max_length=100, verbose_name='Город')
    verification = models.BooleanField(default=False, verbose_name='Верификации')

    def count_news(self):
        pass

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = (
            ("can_publish", "Может публиковать"),
            ("can_visit_profile", "Может зайти в личный кабинет"),
        )

app_news/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import News, Comments


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['name', 'content']


class NewsTagsForm(NewsForm):
    tagss = forms.CharField(max_length=20, required=False)

    class Meta(NewsForm.Meta):
        fields = NewsForm.Meta.fields + ['tagss', ]


class CommentsFormAnonym(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['user_name', 'text', 'news']
        widgets = {'news': forms.HiddenInput()}


class CommentsFormRegist(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['user_name', 'text', 'news']
        widgets = {'news': forms.HiddenInput()}


class RegisterForm(UserCreationForm):
    phone = forms.CharField(max_length=20, help_text='Телефон')
    city = forms.CharField(max_length=100, help_text='Город')

    class Meta:
        model = User
        fields = ('username', 'phone', 'city', 'password1', 'password2',)


class FindTagsForm(forms.Form):
    date = forms.DateTimeField(input_formats=['%Y-%m-%d'], required=False)
    tags = forms.CharField(required=False)

app_news/views.py
from datetime import datetime

from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import FormMixin, CreateView, UpdateView

from .models import News, Profile, Tag
from .forms import CommentsFormRegist, RegisterForm, NewsTagsForm, FindTagsForm


class NewsListView(ListView):
    model = News
    template_name = 'news_list.html'
    context_object_name = 'news_list'
    form_class = FindTagsForm

    def get_queryset(self):
        queryset = super(NewsListView, self).get_queryset().all()
        if 'tag' in self.request.GET:
            tag = self.request.GET.get('tag')
            tag_id = Tag.objects.get(name=tag) if tag is not None else None
            queryset = queryset.filter(tags=tag_id)
        if 'date' in self.request.GET:
            date = self.request.GET.get('date')
            date_datetime = datetime.strptime(date, '%Y-%m-%d') if date is not None else None
            queryset = queryset.filter(updated_at__date=date_datetime)
        return queryset


class NewsCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'app_news.view_news'
    form_class = NewsTagsForm
    template_name = 'app_news/create.html'

    def form_valid(self, form):
        news = form.save()
        tags_array = form.cleaned_data['tagss'].split(' ')
        for tag in tags_array:
            cur_tag, is_create = Tag.objects.get_or_create(name=tag)
            news.tags.add(cur_tag)
        return super(NewsCreate, self).form_valid(form)


class NewsFormEdit(UpdateView):
    form_class = NewsTagsForm
    template_name = 'app_news/edit.html'
    queryset = News.objects.all()

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(News, id=id_)

    def form_valid(self, form):
        news = form.save()
        news.updated_at = datetime.now()
        tags_array = form.cleaned_data['tagss'].split(' ')
        for tag in tags_array:
            cur_tag, is_create = Tag.objects.get_or_create(name=tag)
            news.tags.add(cur_tag)
        return super().form_valid(form)


class NewsDetailFormView(FormMixin, DetailView):
    template_name = 'app_news/news_detail.html'
    model = News
    form_class = CommentsFormRegist

    def get_success_url(self):
        return reverse('news-detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super(NewsDetailFormView, self).get_context_data(**kwargs)
        form = CommentsFormRegist(initial={
            'post': self.object,
            'news': self.object,
        })
        if self.request.user.is_authenticated:
            form.fields['user_name'] = forms.CharField(widget=forms.HiddenInput(), initial='None')
        context['comment_form'] = form
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        if self.request.user.is_authenticated:
            obj.author = self.request.user
            obj.user_name = self.request.user.username
        else:
            obj.author = None
        obj.save()
        return super(NewsDetailFormView, self).form_valid(obj)


class MyLoginView(LoginView):
    template_name = 'users/login.html'


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('news')


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        user = form.save()
        phone = form.cleaned_data.get('phone')
        city = form.cleaned_data.get('city')
        Profile.objects.create(
            user=user,
            city=city,
            phone=phone,
        )
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        group = Group.objects.get(name='Пользователи')
        group.user_set.add(user)
        user = authenticate(username=username, password=raw_password)
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
        return super(RegisterView, self).form_valid(form)

    def get_success_url(self):
        return reverse('news')


class ProfileView(PermissionRequiredMixin, TemplateView):
    permission_required = 'app_news.can_visit_profile'
    template_name = 'users/profile.html'

app_news/templates/app_news/create.html
{% extends "main.html" %}

{% block title %}Создание{% endblock %}

{% block content %}
<h2>Создание</h2>
<form method="post" action="{% url 'news-create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
</form>
{% endblock %}

app_news/templates/app_news/edit.html
{% extends "main.html" %}

{% block title %}Редактирование{% endblock %}

{% block content %}
<h2>Редактирование</h2>
<form method="post" action="{% url 'news-edit' object.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

app_news/templates/app_news/news_detail.html
{% extends "main.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<h3>{{ object.name }}</h3>
<p>{{ object.content }}</p>
{% if object.tags.all %}
<p>Тэги:
    {% for tag in object.tags.all%}
    {{tag.name}},
    {% endfor %}
</p>
{% endif %}
<p>Последний раз обновленно: {{ object.updated_at }}</p>
<form method="post" action="{% url 'news-detail' object.id %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<ul>
    {% for comment in object.comments.all %}
    <li>
        <p>{{ comment.user_name }}{% if comment.author is None %}: анонимно{% endif %}</p>
        <p>{{ comment.text }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app_news/templates/app_news/news_list.html
{% extends "main.html" %}

{% block head %}
<!--<meta charset="utf-8">-->
<!--<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
<!--<title>Static Example</title>-->

<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"-->
<!--        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"-->
<!--        crossorigin="anonymous"></script>-->

<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"-->
<!--      integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous"/>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"-->
<!--        integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>-->
{% endblock %}


{% block content %}
<!--<form action="{% url 'news' %}" method="POST">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <button type="submit">Найти</button>-->
<!--</form>-->

<!--<script>-->
<!--    $(function () {-->
<!--        $("#id_date").datepicker({-->
<!--            format: 'yyyy-mm-dd',-->
<!--        });-->
<!--    });-->
<!--</script>-->

{% if news_list %}
<ul>
    {% for new in news_list %}
    {% if new.active %}
    <li><a href="{% url 'news-detail' new.id %}"> {{ new.name }} </a>
        {% if new.tags.all %}
        <p>Тэги:
            {% for tag in new.tags.all%}
            {{tag.name}},
            {% endfor %}
        </p>
        {% endif %}
    </li>
    {% endif %}
    {% endfor %}
</ul>
{% else %}
<p>Новостей нет</p>
{% endif %}
{% endblock %}